// <auto-generated />
using System;
using HotelApi.src.HotelApi.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HotelApi.Migrations
{
    [DbContext(typeof(HotelDbContext))]
    [Migration("20251119101913_ChangedMapper")]
    partial class ChangedMapper
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HotelApi.src.HotelApi.Domain.Entities.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BookingId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExtraBedsCount")
                        .HasColumnType("integer");

                    b.Property<int?>("InvoiceId")
                        .HasColumnType("integer");

                    b.Property<int>("NumPersons")
                        .HasColumnType("integer");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("BookingId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("RoomId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            BookingId = 1,
                            CreatedAt = new DateTime(2025, 1, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 1,
                            EndDate = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExtraBedsCount = 0,
                            InvoiceId = 1,
                            NumPersons = 2,
                            RoomId = 1,
                            StartDate = new DateTime(2024, 2, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            TotalPrice = 240m,
                            UpdatedAt = new DateTime(2025, 1, 11, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            BookingId = 2,
                            CreatedAt = new DateTime(2025, 2, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 2,
                            EndDate = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExtraBedsCount = 1,
                            InvoiceId = 2,
                            NumPersons = 3,
                            RoomId = 2,
                            StartDate = new DateTime(2024, 3, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            TotalPrice = 500m,
                            UpdatedAt = new DateTime(2025, 2, 6, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("HotelApi.src.HotelApi.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CustomerId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "john@example.com",
                            Name = "John Doe",
                            Phone = "111-222",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CustomerId = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sarah@example.com",
                            Name = "Sarah Connor",
                            Phone = "333-444",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("HotelApi.src.HotelApi.Domain.Entities.Invoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InvoiceId"));

                    b.Property<decimal>("AmountDue")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("BookingId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("InvoiceId");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.ToTable("Invoices");

                    b.HasData(
                        new
                        {
                            InvoiceId = 1,
                            AmountDue = 240m,
                            BookingId = 1,
                            IssueDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1
                        },
                        new
                        {
                            InvoiceId = 2,
                            AmountDue = 500m,
                            BookingId = 2,
                            IssueDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1
                        });
                });

            modelBuilder.Entity("HotelApi.src.HotelApi.Domain.Entities.PaymentRecord", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("AmountPaid")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("text");

                    b.HasKey("PaymentId");

                    b.HasIndex("InvoiceId");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            PaymentId = 1,
                            AmountPaid = 240m,
                            InvoiceId = 1,
                            PaymentDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PaymentMethod = "Credit Card"
                        });
                });

            modelBuilder.Entity("HotelApi.src.HotelApi.Domain.Entities.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoomId"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Amenities")
                        .HasColumnType("text");

                    b.Property<int>("BaseCapacity")
                        .HasColumnType("integer");

                    b.Property<int>("MaxExtraBeds")
                        .HasColumnType("integer");

                    b.Property<decimal>("PricePerNight")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("RoomId");

                    b.HasIndex("RoomNumber")
                        .IsUnique();

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            RoomId = 1,
                            Active = true,
                            BaseCapacity = 1,
                            MaxExtraBeds = 0,
                            PricePerNight = 80m,
                            RoomNumber = "101",
                            Type = 0
                        },
                        new
                        {
                            RoomId = 2,
                            Active = true,
                            BaseCapacity = 1,
                            MaxExtraBeds = 1,
                            PricePerNight = 100m,
                            RoomNumber = "102",
                            Type = 0
                        },
                        new
                        {
                            RoomId = 3,
                            Active = true,
                            BaseCapacity = 1,
                            MaxExtraBeds = 1,
                            PricePerNight = 100m,
                            RoomNumber = "103",
                            Type = 0
                        },
                        new
                        {
                            RoomId = 4,
                            Active = true,
                            BaseCapacity = 2,
                            MaxExtraBeds = 0,
                            PricePerNight = 150m,
                            RoomNumber = "201",
                            Type = 0
                        },
                        new
                        {
                            RoomId = 5,
                            Active = true,
                            BaseCapacity = 2,
                            MaxExtraBeds = 1,
                            PricePerNight = 150m,
                            RoomNumber = "202",
                            Type = 0
                        },
                        new
                        {
                            RoomId = 6,
                            Active = true,
                            BaseCapacity = 2,
                            MaxExtraBeds = 2,
                            PricePerNight = 150m,
                            RoomNumber = "203",
                            Type = 0
                        });
                });

            modelBuilder.Entity("HotelApi.src.HotelApi.Domain.Entities.Booking", b =>
                {
                    b.HasOne("HotelApi.src.HotelApi.Domain.Entities.Customer", "Customer")
                        .WithMany("Bookings")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HotelApi.src.HotelApi.Domain.Entities.Room", "Room")
                        .WithMany("Bookings")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("HotelApi.src.HotelApi.Domain.Entities.Invoice", b =>
                {
                    b.HasOne("HotelApi.src.HotelApi.Domain.Entities.Booking", "Booking")
                        .WithOne("Invoice")
                        .HasForeignKey("HotelApi.src.HotelApi.Domain.Entities.Invoice", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("HotelApi.src.HotelApi.Domain.Entities.PaymentRecord", b =>
                {
                    b.HasOne("HotelApi.src.HotelApi.Domain.Entities.Invoice", "Invoice")
                        .WithMany("Payments")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("HotelApi.src.HotelApi.Domain.Entities.Booking", b =>
                {
                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("HotelApi.src.HotelApi.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("HotelApi.src.HotelApi.Domain.Entities.Invoice", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("HotelApi.src.HotelApi.Domain.Entities.Room", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
